export const CITIES = {
    // BRUXELLES: 'Bruxelles',
    NANTES: 'Nantes',
    PARIS: "Paris",
    TOULOUSE: 'Toulouse',
};

export const DAYS = {
    VENDREDI: 'Vendredi 14 octobre',
    SAMEDI: 'Samedi 15 octobre',
    DIMANCHE: 'Dimanche 15 octobre',
};

export const CINEMAS = {
    // BRUXELLES: {
    //     name: 'Cinéma Bruxelles (todo)',
    //     address: '98 Bd du Montparnasse',
    //     zip: '75014',
    //     city: 'Paris',
    //     ticketingOpenDate: '',
    //     ticketingRedirection: '',
    // },
    NANTES: {
        name: 'Cinéma centre commercial Pôle Sud',
        address: 'route de Clisson',
        zip: '44115',
        city: 'Basse Goulaine',
        ticketingOpenDate: '2022-09-15',
        ticketingRedirection: '',
    },
    PARIS: {
        name: 'Cinéma les 7 Parnassiens',
        address: '98 Bd du Montparnasse',
        zip: '75014',
        city: 'Paris',
        ticketingOpenDate: '2022-09-15',
        ticketingRedirection: 'https://google.com',
    },
    TOULOUSE_BORDEROUGE: {
        name: 'Utopia Borderouge',
        address: '59, avenue Maurice Bourgès-Maunoury',
        zip: '32200',
        city: 'Toulouse',
        ticketingOpenDate: '',
        ticketingRedirection: '',
    },
    TOULOUSE_TOURNEFEUILLE: {
        name: 'Utopia Tournefeuille',
        address: 'impasse du Château',
        zip: '31170',
        city: 'Tournefeuille',
        ticketingOpenDate: '',
        ticketingRedirection: '',
    },
}

export const films = [
    {
        edition: 2022,
        title: "En guerre",
        author: "Stéphane Brizé",
        releaseDate: 2018,
        duration: "1h53",
        originalTitle: null,
        theme : "Transition écologique, atout ou péril pour l'emploi ?",
        image: { summary: "en-guerre.jpg", programmation: "en-guerre.jpeg"},
        summary: "Malgré de lourds sacrifices financiers de la part des salariés et un bénéfice record de leur entreprise, la direction de l’usine Perrin Industrie décide néanmoins la fermeture totale du site. Accord bafoué, promesses non respectées, les 1100 salariés, emmenés par leur porte‑parole Laurent Amédéo, refusent cette décision brutale et vont tout tenter pour sauver leur emploi.",
        trailer: 'qOB9mroJ1zU',
        debat: 'Le thème et les intervenants seront prochainement communiqués.',
        redirect: '/films/en-guerre',
        styles: { color: "text-dark"},
        cities: [
            { 
                city: CITIES.PARIS, 
                day: DAYS.SAMEDI, 
                moment: "14h",
                animator: null,
                participants: [
                    { name: null, description: "description 1"},
                    { name: null, description: "description 2"},
                ],
                cinema: CINEMAS.PARIS,
            }, 
            { 
                city: CITIES.NANTES, 
                day: DAYS.SAMEDI, 
                moment: "14h",
                animator: null,
                participants: [
                    { name: null, description: "description 1"},
                    { name: null, description: "description 2"},
                ],
                cinema: CINEMAS.NANTES,
            }, 
            { 
                city: CITIES.TOULOUSE, 
                day: DAYS.SAMEDI, 
                moment: "15h30",
                animator: null,
                participants: [
                    { name: null, description: "description 1"},
                    { name: null, description: "description 2"},
                ],
                cinema: CINEMAS.TOULOUSE_BORDEROUGE,
            }, 
        ]
    },
    {
        edition: 2022,
        title: "Goliath",
        author: "Frédéric Tellier",
        releaseDate: 2022,
        duration: "2h02",
        originalTitle: null,
        theme : "Modèles agricoles : la faim justifie-t-elle les moyens ?",
        image: { summary: "goliath.jpg", programmation: "goliath.jpg"},
        summary: "France, professeure de sport le jour, ouvrière la nuit, milite activement contre l’usage des pesticides. Patrick, obscur et solitaire avocat parisien, est spécialiste en droit environnemental. Mathias, lobbyiste brillant et homme pressé, défend les intérêts d’un géant de l’agrochimie. Suite à l’acte radical d’une anonyme, ces trois destins, qui n’auraient jamais dû se croiser, vont se bousculer, s’entrechoquer et s’embraser.", 
        trailer: "I3gZ6Iz6yQI",
        debat: 'Le thème et les intervenants seront prochainement communiqués.',
        redirect: '/films/goliath',
        styles: { color: "text-dark"},
        cities: [
            { 
                city: CITIES.PARIS, 
                day: DAYS.DIMANCHE, 
                moment: "11h",
                animator: null,
                participants: [
                    { name: null, description: "description 1"},
                    { name: null, description: "description 2"},
                ],
                cinema: CINEMAS.PARIS,
            }, 
            { 
                city: CITIES.NANTES, 
                day: DAYS.DIMANCHE, 
                moment: "13h30",
                animator: null,
                participants: [
                    { name: null, description: "description 1"},
                    { name: null, description: "description 2"},
                ],
                cinema: CINEMAS.NANTES,
            }, 
            { 
                city: CITIES.TOULOUSE, 
                day: DAYS.DIMANCHE, 
                moment: "11h00",
                animator: null,
                participants: [
                    { name: null, description: "description 1"},
                    { name: null, description: "description 2"},
                ],
                cinema: CINEMAS.TOULOUSE_BORDEROUGE,
            }, 
        ]
    },
    {
        edition: 2022,
        title: "Le garçon qui dompta le vent",
        author: "Chiwetel Ejiofor",
        releaseDate: 2021,
        duration: "1h35",
        originalTitle: 'The Boy Who Harnessed the Wind',
        theme : "Inégalités climatiques : quelles solutions pour les pays les plus vulnérables ?",
        image: { summary: "le-garcon-qui-dompta-le-vent.jpg", programmation: "garcon-qui-dompta-le-vent.jpg" },
        summary: "Contre toute attente, un jeune Malawite de 13 ans invente un système ingénieux pour sauver sa famille et son village de la famine. Inspiré de l'histoire vraie de William Kamkwamba et adapté de son roman best-seller.", 
        trailer: "nPkr9HmglG0",
        debat: 'Le thème et les intervenants seront prochainement communiqués.',
        redirect: '/films/garcon-qui-dompta-le-vent',
        styles: { color: "text-dark"},
        cities: [
            { 
                city: CITIES.PARIS, 
                day: DAYS.VENDREDI, 
                moment: "14h",
                animator: null,
                participants: [
                    { name: null, description: "description 1"},
                    { name: null, description: "description 2"},
                ],
                cinema: CINEMAS.PARIS,
            }, 
            { 
                city: CITIES.NANTES, 
                day: DAYS.VENDREDI, 
                moment: "14h",
                animator: null,
                participants: [
                    { name: null, description: "description 1"},
                    { name: null, description: "description 2"},
                ],
                cinema: CINEMAS.NANTES,
            }, 
            { 
                city: CITIES.TOULOUSE, 
                day: DAYS.VENDREDI, 
                moment: "14h",
                animator: null,
                participants: [
                    { name: null, description: "description 1"},
                    { name: null, description: "description 2"},
                ],
                cinema: CINEMAS.TOULOUSE_BORDEROUGE,
            }, 
        ]
    },
    {
        edition: 2022,
        title: "Les Fils de l'homme",
        author: 'Alfonso Cuarón',
        releaseDate: 2006,
        duration: "1h50",
        originalTitle: 'Children of Men',
        theme : "Réfugiés climatiques : quelles frontières dans un monde en crise ?",
        image: { summary: "les-fils-de-l-homme.jpg", programmation: "les-fils-de-lhomme.png"},
        summary: "Dans une société futuriste où les êtres humains ne parviennent plus à se reproduire, l'annonce de la mort de la plus jeune personne, âgée de 18 ans, met la population en émoi. Au même moment, une femme tombe enceinte - un fait qui ne s'est pas produit depuis une vingtaine d'années - et devient par la même occasion la personne la plus enviée et la plus recherchée de la Terre. Un homme est chargé de sa protection... Film interdit aux moins de 12 ans.", 
        trailer: "2VT2apoX90o",
        debat: 'Le thème et les intervenants seront prochainement communiqués.',
        redirect: '/films/les-fils-de-l-homme',
        styles: { color: "text-dark"},
        cities: [
            { 
                city: CITIES.PARIS, 
                day: DAYS.SAMEDI, 
                moment: "20h",
                animator: null,
                participants: [
                    { name: null, description: "description 1"},
                    { name: null, description: "description 2"},
                ],
                cinema: CINEMAS.PARIS,
            }, 
            { 
                city: CITIES.NANTES, 
                day: DAYS.SAMEDI, 
                moment: "17h45",
                animator: null,
                participants: [
                    { name: null, description: "description 1"},
                    { name: null, description: "description 2"},
                ],
                cinema: CINEMAS.NANTES,
            }, 
            { 
                city: CITIES.TOULOUSE, 
                day: DAYS.DIMANCHE, 
                moment: "20h00",
                animator: null,
                participants: [
                    { name: null, description: "description 1"},
                    { name: null, description: "description 2"},
                ],
                cinema: CINEMAS.TOULOUSE_BORDEROUGE,
            }, 
        ]
    },
    {
        edition: 2022,
        title: "Sans filtre",
        author: "Ruben Östlund",
        releaseDate: 2022,
        duration: "2h29",
        originalTitle: 'Triangle of Sadness',
        theme : "Urgent : société sous influence cherche nouveaux modèles !",
        image: { summary: "sans-filtre.jpg", programmation: "sans-filtre.jpg"},
        summary: "Après la Fashion Week, Carl et Yaya, couple de mannequins et influenceurs, sont invités sur un yacht pour une croisière de luxe. Tandis que l’équipage est aux petits soins avec les vacanciers, le capitaine refuse de sortir de sa cabine alors que le fameux dîner de gala approche. Les événements prennent une tournure inattendue et les rapports de force s'inversent lorsqu'une tempête se lève et met en danger le confort des passagers. Palme d'Or au Festival de Cannes 2022.", 
        trailer: "gaOdbOdWCVA",
        debat: 'Le thème et les intervenants seront prochainement communiqués.',
        redirect: '/films/sans-filtre',
        styles: { color: "text-dark"},
        cities: [
            { 
                city: CITIES.PARIS, 
                day: DAYS.DIMANCHE, 
                moment: "17h30",
                animator: null,
                participants: [
                    { name: null, description: "description 1"},
                    { name: null, description: "description 2"},
                ],
                cinema: CINEMAS.PARIS,
            }, 
            { 
                city: CITIES.NANTES, 
                day: DAYS.DIMANCHE, 
                moment: "17h10",
                animator: null,
                participants: [
                    { name: null, description: "description 1"},
                    { name: null, description: "description 2"},
                ],
                cinema: CINEMAS.NANTES,
            }, 
        ]
    },
    {
        edition: 2022,
        title: "Soleil vert",
        author: "Richard Fleischer",
        releaseDate: 1974,
        duration: "1h37",
        originalTitle: 'Soylent Green',
        theme : "Plus d'humains, moins d'humanité ?",
        image: { summary: 'soleil-vert.jpg', programmation: "soleil-vert.jpeg"}, 
        summary: "New York en 2022. Un brouillard a envahi la surface du globe, tuant la végétation et la plupart des espèces animales. D'un côté, les nantis qui peuvent avoir accès à la nourriture rare et très chère. De l'autre, les affamés nourris d'un produit synthétique, le soylent, rationné par le gouvernement... Lors d'une émeute, le président de soylent trouve la mort et Thorn , un flic opiniâtre, est chargé de l'enquête...", 
        trailer: "N_jGOKYHxaQ",
        debat: 'Le thème et les intervenants seront prochainement communiqués.',
        redirect: '/films/soleil-vert',
        styles: { color: "text-dark"},
        cities: [
            { 
                city: CITIES.PARIS, 
                day: DAYS.VENDREDI, 
                moment: "20h",
                animator: null,
                participants: [
                    { name: null, description: "description 1"},
                    { name: null, description: "description 2"},
                ],
                cinema: CINEMAS.PARIS,
            }, 
            { 
                city: CITIES.NANTES, 
                day: DAYS.VENDREDI, 
                moment: "19h30",
                animator: null,
                participants: [
                    { name: null, description: "description 1"},
                    { name: null, description: "description 2"},
                ],
                cinema: CINEMAS.NANTES,
            }, 
            { 
                city: CITIES.TOULOUSE, 
                day: DAYS.VENDREDI, 
                moment: "20h30",
                animator: null,
                participants: [
                    { name: null, description: "description 1"},
                    { name: null, description: "description 2"},
                ],
                cinema: CINEMAS.TOULOUSE_BORDEROUGE,
            }, 
        ]
    },
];